### ISSUE TITLE
Columns in RDFa output

### ISSUE THREAD

**Issue by rgcmme** [albaizq/Themis#1]
The header of the columns "Result" and "Ontology" in the RDFa output is switched.

I would also put the "Ontology" column the first one, to leave together the test and the result. Or even write a header "Results for ontology xxxxx" and then include the table with the results for that ontology but only showing test+result.

**Comment by albaizq** [comment]
Solved the columns order.  Changed the order of the columns to Ontology, Test, Results. No header added since the same table could store tests from multiple ontologies
